# Generated by Django 2.2.24 on 2024-06-13 10:02

from django.db import migrations
import phonenumbers

def normalize_owner_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        owner_number = flat.owners_phonenumber
        parsed_owner_phone = phonenumbers.parse(owner_number, 'RU')
        if phonenumbers.is_valid_number(parsed_owner_phone):
            flat.owner_pure_phone = parsed_owner_phone
            flat.save()

def move_backward(apps, schema_editor):
    Flat = apps.get_mdoel('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        flat.owner_pure_phone = None
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20240613_1244'),
    ]

    operations = [
        migrations.RunPython(normalize_owner_phone, move_backward)
    ]
