# Generated by Django 2.2.24 on 2024-06-18 10:41

from django.db import migrations

def move_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            name=flat.owner,
            defaults={
                "owners_phonenumber": flat.owners_phonenumber,
                "owner_pure_phone": flat.owner_pure_phone
            }
        )
        

def move_backwards(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.all().delete() 


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
        migrations.RunPython(move_owners, move_backwards)
    ]
